spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Laways/spring_cloud_config
          username: Laways
          password: 19890809lw
          basedir: D:\git_repository\springCloudConfig
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8100
management:
  endpoints:
    web:
      exposure:
        include: "*"
#management:
#  security:
#    enabled: false
